Use autosrc instead of hand-crafting generation rules.

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -1,4 +1,7 @@
 include $(top_srcdir)/m4/memdeb.ami
+include $(top_srcdir)/m4/autosrc.ami
+
+include $(top_srcdir)/autosrc/Makefile.ami
 
 UCL_DIR=$(top_srcdir)/external/libucl
 
@@ -6,8 +9,16 @@ bin_PROGRAMS=rtpproxy rtpproxy_debug
 if BUILD_OBJCK
 noinst_PROGRAMS=rtpp_objck rtpp_objck_perf
 endif
-BASE_SOURCES=main.c rtp.h rtpp_server.c rtpp_server.h \
-  rtpp_defines.h rtpp_log.h rtpp_record.c rtpp_record.h rtpp_session.h \
+
+RTPP_AUTOSRC_SOURCES = rtpp_command_rcache.h rtpp_log_obj.h \
+  rtpp_pcnt_strm.h rtpp_pcount.h rtpp_pipe.h rtpp_port_table.h rtpp_record.h \
+  rtpp_ringbuf.h rtpp_sessinfo.h rtpp_socket.h rtpp_timed_task.h rtpp_ttl.h
+
+RTPP_AUTOSRC_SOURCES_S = rtpp_netaddr.h rtpp_pearson_perfect.h rtpp_refcnt.h \
+  rtpp_server.h rtpp_stats.h rtpp_stream.h rtpp_timed.h
+
+BASE_SOURCES=main.c rtp.h rtpp_server.c \
+  rtpp_defines.h rtpp_log.h rtpp_record.c rtpp_session.h \
   rtpp_util.c rtpp_util.h rtp.c rtp_resizer.c rtp_resizer.h rtpp_session.c \
   rtpp_command.c rtpp_command.h rtpp_network.h rtpp_network.c \
   rtpp_syslog_async.c rtpp_syslog_async.h rtpp_notify.c rtpp_notify.h \
@@ -18,29 +29,30 @@ BASE_SOURCES=main.c rtp.h rtpp_server.c rtpp_server.h \
   rtpp_command_parse.c rtpp_command_parse.h rtpp_command_copy.c \
   rtpp_command_copy.h rtpp_command_ul.c rtpp_command_ul.h \
   rtpp_hash_table.c rtpp_hash_table.h rtpp_types.h config_pp.h rtpp_stats.c \
-  rtpp_stats.h rtpp_cfg_stable.h rtpp_command_stats.h rtpp_command_stats.c \
+  rtpp_cfg_stable.h rtpp_command_stats.h rtpp_command_stats.c \
   rtp_info.h rtpp_command_private.h rtpp_controlfd.h rtpp_controlfd.c \
   rtpp_list.h rtpp_command_stream.h rtpp_command_stream.c rtpp_timed.c \
-  rtpp_timed.h rtpp_analyzer.c rtpp_analyzer.h rtp_analyze.c rtp_analyze.h \
+  rtpp_analyzer.c rtpp_analyzer.h rtp_analyze.c rtp_analyze.h \
   rtpp_command_query.c rtpp_command_query.h rtpp_pearson.c rtpp_pearson.h \
-  rtpp_refcnt.c rtpp_refcnt.h rtpp_command_rcache.c rtpp_command_rcache.h \
+  rtpp_refcnt.c rtpp_command_rcache.c \
   rtpp_tnotify_set.c rtpp_tnotify_set.h rtpp_tnotify_tgt.h rtp_packet.h \
   rtpp_time.c rtpp_time.h \
-  rtpp_sessinfo.c rtpp_sessinfo.h rtpp_weakref.c rtpp_weakref.h \
-  rtpp_proc_servers.h rtpp_proc_servers.c rtpp_stream.h rtpp_stream.c \
+  rtpp_sessinfo.c rtpp_weakref.c rtpp_weakref.h \
+  rtpp_proc_servers.h rtpp_proc_servers.c rtpp_stream.c \
   rtpp_genuid.h rtpp_genuid.c rtpp_genuid_singlet.h rtpp_genuid_singlet.c \
-  rtpp_log_obj.h rtpp_log_obj.c rtpp_socket.c rtpp_socket.h \
-  rtpp_ttl.c rtpp_ttl.h rtpp_proc_ttl.h rtpp_proc_ttl.c rtpp_pipe.h \
-  rtpp_pipe.c rtpp_pcount.h rtpp_pcount.c rtpp_debug.h rtpp_monotime.h \
-  rtpp_monotime.c rtpp_mallocs.c rtpp_mallocs.h rtpp_pcnt_strm.h \
-  rtpp_pcnt_strm.c rtpp_endian.h rtpp_ringbuf.c rtpp_ringbuf.h \
+  rtpp_log_obj.c rtpp_socket.c \
+  rtpp_ttl.c rtpp_proc_ttl.h rtpp_proc_ttl.c \
+  rtpp_pipe.c rtpp_pcount.c rtpp_debug.h rtpp_monotime.h \
+  rtpp_monotime.c rtpp_mallocs.c rtpp_mallocs.h \
+  rtpp_pcnt_strm.c rtpp_endian.h rtpp_ringbuf.c \
   rtpp_command_delete.c rtpp_command_delete.h rtpp_command_record.c \
-  rtpp_command_record.h rtpp_port_table.c rtpp_port_table.h rtpp_acct.c \
+  rtpp_command_record.h rtpp_port_table.c rtpp_acct.c \
   rtpp_acct.h rtpp_stats.h rtpp_bindaddrs.c rtpp_bindaddrs.h rtpp_ssrc.h \
-  rtpp_netaddr.c rtpp_netaddr.h rtpp_acct_pipe.h rtpp_command_play.c \
+  rtpp_netaddr.c rtpp_acct_pipe.h rtpp_command_play.c \
   rtpp_command_play.h rtpp_command_ver.h rtpp_command_ver.c \
-  rtpp_pearson_perfect.c rtpp_pearson_perfect.h rtpp_acct_rtcp.h \
-  rtpp_acct_rtcp.c rtpp_cfile.c rtpp_cfile.h rtpp_ucl.c rtpp_ucl.h
+  rtpp_pearson_perfect.c rtpp_acct_rtcp.h \
+  rtpp_acct_rtcp.c rtpp_cfile.c rtpp_cfile.h rtpp_ucl.c rtpp_ucl.h \
+  $(RTPP_AUTOSRC_SOURCES) $(RTPP_AUTOSRC_SOURCES_S)
 
 rtpproxy_LDADD=-lm -lpthread @LIBS_ELPERIODIC@ $(top_srcdir)/libucl/libucl.a
 rtpproxy_debug_LDADD=-lm -lpthread @LIBS_ELPERIODIC@ $(top_srcdir)/libucl/libucl_debug.a \
@@ -48,7 +60,8 @@ rtpproxy_debug_LDADD=-lm -lpthread @LIBS_ELPERIODIC@ $(top_srcdir)/libucl/libucl
 rtpproxy_debug_LDFLAGS=-static -Wl,--export-dynamic
 
 if ENABLE_MODULE_IF
-BASE_SOURCES+=rtpp_module_if.c rtpp_module_if.h rtpp_module.h
+RTPP_AUTOSRC_SOURCES += rtpp_module_if.h
+BASE_SOURCES += rtpp_module_if.c rtpp_module.h
 rtpproxy_LDADD+=@LIBS_DL@
 rtpproxy_LDFLAGS=-Wl,--export-dynamic
 endif
@@ -64,19 +77,6 @@ endif
 SRCS_MEMDEB_CORE = $(RTPP_MEMDEB_CORESRCS) rtpp_memdeb_stats.h rtpp_memdeb_test.c
 SRCS_DEBUG=	$(SRCS_MEMDEB_CORE) rtpp_stacktrace.c rtpp_stacktrace.h
 
-SRCS_AUTOGEN=rtpp_timed_fin.c rtpp_timed_fin.h rtpp_stream_fin.c \
-  rtpp_stream_fin.h rtpp_server_fin.c rtpp_server_fin.h rtpp_refcnt_fin.c \
-  rtpp_refcnt_fin.h rtpp_log_obj_fin.c rtpp_log_obj_fin.h \
-  rtpp_command_rcache_fin.c rtpp_command_rcache_fin.h rtpp_socket_fin.c \
-  rtpp_socket_fin.h rtpp_record_fin.c rtpp_record_fin.h rtpp_ttl_fin.c \
-  rtpp_ttl_fin.h rtpp_pipe_fin.c rtpp_pipe_fin.h rtpp_pcount_fin.c \
-  rtpp_pcount_fin.h rtpp_sessinfo_fin.c rtpp_sessinfo_fin.h \
-  rtpp_pcnt_strm_fin.h rtpp_pcnt_strm_fin.c rtpp_ringbuf_fin.c \
-  rtpp_ringbuf_fin.h rtpp_module_if_fin.h rtpp_module_if_fin.c \
-  rtpp_port_table_fin.c rtpp_port_table_fin.h \
-  rtpp_netaddr_fin.c rtpp_netaddr_fin.h \
-  rtpp_stats_fin.c rtpp_stats_fin.h rtpp_pearson_perfect_fin.c \
-  rtpp_pearson_perfect_fin.h rtpp_timed_task_fin.c rtpp_timed_task_fin.h
 rtpproxy_SOURCES=$(BASE_SOURCES) $(SRCS_AUTOGEN)
 rtpproxy_debug_SOURCES=$(rtpproxy_SOURCES) $(SRCS_DEBUG)
 rtpp_objck_perf_LDADD=-lm -lpthread @LIBS_ELPERIODIC@
@@ -92,8 +92,10 @@ RTPP_COMMON_CPPFLAGS=-DCFILE_PATH='"$(sysconfdir)/@PACKAGE@.conf"' \
   -DMDDIR_PATH='"$(libdir)/@PACKAGE@"' -I$(UCL_DIR)/include
 EXTRA_CFLAGS=-Werror=implicit-function-declaration -Wall
 
+EXTRA_CPPFLAGS = -I$(RTPP_AUTOSRC_DIR)
+
 if BUILD_ELPERIODIC
-EXTRA_CPPFLAGS=-I$(top_srcdir)/libelperiodic/src
+EXTRA_CPPFLAGS += -I$(top_srcdir)/libelperiodic/src
 endif
 
 rtpproxy_debug_CFLAGS=$(EXTRA_CFLAGS) $(RTPP_MEMDEB_CFLAGS)
@@ -110,121 +112,41 @@ rtpp_objck_CPPFLAGS=$(rtpp_objck_perf_CPPFLAGS) $(RTPP_MEMDEB_CPPFLAGS) -DMEMDEB
 
 DEFS=	-Wall @DEFS@
 
-CLEANFILES= $(SRCS_AUTOGEN) *.gcda *.gcno
-BUILT_SOURCES= $(SRCS_AUTOGEN)
+CLEANFILES= *.gcda *.gcno
+#BUILT_SOURCES= $(_SRCS_AUTOGEN)
 
 GENFINCODE= $(top_srcdir)/src/genfincode.sh
 GENFINCODE_S= $(top_srcdir)/src/genfincode_stat.sh
 
-rtpp_timed_fin.c: $(GENFINCODE_S) rtpp_timed.h
-	$(GENFINCODE_S) rtpp_timed.h rtpp_timed_fin.h rtpp_timed_fin.c
-
-rtpp_timed_fin.h: rtpp_timed_fin.c
-
-rtpp_timed_task_fin.c: $(GENFINCODE) rtpp_timed_task.h
-	$(GENFINCODE) rtpp_timed_task.h rtpp_timed_task_fin.h rtpp_timed_task_fin.c
-
-rtpp_timed_task_fin.h: rtpp_timed_task_fin.c
-
-rtpp_stream_fin.c: $(GENFINCODE_S) rtpp_stream.h
-	$(GENFINCODE_S) rtpp_stream.h rtpp_stream_fin.h rtpp_stream_fin.c
-
-rtpp_stream_fin.h: rtpp_stream_fin.c
-
-rtpp_server_fin.c: $(GENFINCODE) rtpp_server.h
-	$(GENFINCODE_S) rtpp_server.h rtpp_server_fin.h rtpp_server_fin.c
-
-rtpp_server_fin.h: rtpp_server_fin.c
-
-rtpp_refcnt_fin.c: $(GENFINCODE_S) rtpp_refcnt.h
-	$(GENFINCODE_S) rtpp_refcnt.h rtpp_refcnt_fin.h rtpp_refcnt_fin.c
-
-rtpp_refcnt_fin.h: rtpp_refcnt_fin.c
-
-rtpp_log_obj_fin.c: $(GENFINCODE) rtpp_log_obj.h
-	$(GENFINCODE) rtpp_log_obj.h rtpp_log_obj_fin.h rtpp_log_obj_fin.c
-
-rtpp_log_obj_fin.h: rtpp_log_obj_fin.c
-
-rtpp_command_rcache_fin.c: $(GENFINCODE) rtpp_command_rcache.h
-	$(GENFINCODE) rtpp_command_rcache.h rtpp_command_rcache_fin.h rtpp_command_rcache_fin.c
-
-rtpp_command_rcache_fin.h: rtpp_command_rcache_fin.c
-
-rtpp_socket_fin.c: $(GENFINCODE) rtpp_socket.h
-	$(GENFINCODE) rtpp_socket.h rtpp_socket_fin.h rtpp_socket_fin.c
-
-rtpp_socket_fin.h: rtpp_socket_fin.c
-
-rtpp_record_fin.c: $(GENFINCODE) rtpp_record.h
-	$(GENFINCODE) rtpp_record.h rtpp_record_fin.h rtpp_record_fin.c
-
-rtpp_record_fin.h: rtpp_record_fin.c
-
-rtpp_ttl_fin.c: $(GENFINCODE) rtpp_ttl.h
-	$(GENFINCODE) rtpp_ttl.h rtpp_ttl_fin.h rtpp_ttl_fin.c
-
-rtpp_ttl_fin.h: rtpp_ttl_fin.c
-
-rtpp_pipe_fin.c: $(GENFINCODE) rtpp_pipe.h
-	$(GENFINCODE) rtpp_pipe.h rtpp_pipe_fin.h rtpp_pipe_fin.c
-
-rtpp_pipe_fin.h: rtpp_pipe_fin.c
-
-rtpp_pcount_fin.c: $(GENFINCODE) rtpp_pcount.h
-	$(GENFINCODE) rtpp_pcount.h rtpp_pcount_fin.h rtpp_pcount_fin.c
-
-rtpp_pcount_fin.h: rtpp_pcount_fin.c
-
-rtpp_ringbuf_fin.c: $(GENFINCODE) rtpp_ringbuf.h
-	$(GENFINCODE) rtpp_ringbuf.h rtpp_ringbuf_fin.h rtpp_ringbuf_fin.c
-
-rtpp_ringbuf_fin.h: rtpp_ringbuf_fin.c
-
-rtpp_sessinfo_fin.c: $(GENFINCODE) rtpp_sessinfo.h
-	$(GENFINCODE) rtpp_sessinfo.h rtpp_sessinfo_fin.h rtpp_sessinfo_fin.c
-
-rtpp_sessinfo_fin.h: rtpp_sessinfo_fin.c
-
-rtpp_pcnt_strm_fin.c: $(GENFINCODE) rtpp_pcnt_strm.h
-	$(GENFINCODE) rtpp_pcnt_strm.h rtpp_pcnt_strm_fin.h rtpp_pcnt_strm_fin.c
-
-rtpp_pcnt_strm_fin.h: rtpp_pcnt_strm_fin.c
-
-rtpp_module_if_fin.c: $(GENFINCODE) rtpp_module_if.h
-	$(GENFINCODE) rtpp_module_if.h rtpp_module_if_fin.h rtpp_module_if_fin.c
-
-rtpp_module_if_fin.h: rtpp_module_if_fin.c
-
-rtpp_port_table_fin.c: $(GENFINCODE) rtpp_port_table.h
-	$(GENFINCODE) rtpp_port_table.h rtpp_port_table_fin.h rtpp_port_table_fin.c
-
-rtpp_port_table_fin.h: rtpp_port_table_fin.c
-
-#rtpp_acct_fin.c: $(GENFINCODE) rtpp_acct.h
-#	$(GENFINCODE) rtpp_acct.h rtpp_acct_fin.h rtpp_acct_fin.c
-
-#rtpp_acct_fin.h: rtpp_acct_fin.c
-
-#rtpp_acct_rtcp_fin.c: $(GENFINCODE) rtpp_acct_rtcp.h
-#	$(GENFINCODE) rtpp_acct_rtcp.h rtpp_acct_rtcp_fin.h rtpp_acct_rtcp_fin.c
-
-#rtpp_acct_rtcp_fin.h: rtpp_acct_rtcp_fin.c
-
-rtpp_netaddr_fin.c: $(GENFINCODE_S) rtpp_netaddr.h
-	$(GENFINCODE_S) rtpp_netaddr.h rtpp_netaddr_fin.h rtpp_netaddr_fin.c
-
-rtpp_netaddr_fin.h: rtpp_netaddr_fin.c
-
-rtpp_stats_fin.c: $(GENFINCODE_S) rtpp_stats.h
-	$(GENFINCODE_S) rtpp_stats.h rtpp_stats_fin.h rtpp_stats_fin.c
-
-rtpp_stats_fin.h: rtpp_stats_fin.c
-
-rtpp_pearson_perfect_fin.c: $(GENFINCODE_S) rtpp_pearson_perfect.h
-	$(GENFINCODE_S) rtpp_pearson_perfect.h rtpp_pearson_perfect_fin.h rtpp_pearson_perfect_fin.c
-
-rtpp_pearson_perfect_fin.h: rtpp_pearson_perfect_fin.c
+update_autosrc:
+	@echo "include \$$(top_srcdir)/m4/autosrc.ami" > $(RTPP_AUTOSRC_DIR)/Makefile.ami
+	@echo "SRCS_AUTOGEN = # To be continued..." >> $(RTPP_AUTOSRC_DIR)/Makefile.ami
+	@for f in $(RTPP_AUTOSRC_SOURCES); \
+	do \
+	  ofile="$${f%.h}"; \
+	  if [ $${ofile} = $${f} ]; \
+	  then \
+	    echo "Cannot determine output file name from $${f}" >&2; \
+	    exit 1; \
+	  fi; \
+	  echo "Processing $${f}..."; \
+	  $(GENFINCODE) $${f} $(RTPP_AUTOSRC_DIR)/$${ofile}_fin.h $(RTPP_AUTOSRC_DIR)/$${ofile}_fin.c; \
+	  echo "$${ofile}_AUTOSRCS = \$$(RTPP_AUTOSRC_DIR)/$${ofile}_fin.h \$$(RTPP_AUTOSRC_DIR)/$${ofile}_fin.c" >> $(RTPP_AUTOSRC_DIR)/Makefile.ami; \
+	  echo "SRCS_AUTOGEN += \$$($${ofile}_AUTOSRCS)" >> $(RTPP_AUTOSRC_DIR)/Makefile.ami; \
+	done
+	@for f in $(RTPP_AUTOSRC_SOURCES_S); \
+	do \
+	  ofile="$${f%.h}"; \
+	  if [ $${ofile} = $${f} ]; \
+	  then \
+	    echo "Cannot determine output file name from $${f}" >&2; \
+	    exit 1; \
+	  fi; \
+	  echo "Processing $${f}..."; \
+	  $(GENFINCODE_S) $${f} $(RTPP_AUTOSRC_DIR)/$${ofile}_fin.h $(RTPP_AUTOSRC_DIR)/$${ofile}_fin.c; \
+	  echo "$${ofile}_AUTOSRCS = \$$(RTPP_AUTOSRC_DIR)/$${ofile}_fin.h \$$(RTPP_AUTOSRC_DIR)/$${ofile}_fin.c" >> $(RTPP_AUTOSRC_DIR)/Makefile.ami; \
+	  echo "SRCS_AUTOGEN += \$$($${ofile}_AUTOSRCS)" >> $(RTPP_AUTOSRC_DIR)/Makefile.ami; \
+	done
 
 IPLDIR=$(top_srcdir)/src/ipol
 
